### ISSUE TITLE
HttpRequestException was unhandled by user code (Client project on MainWindow.xaml)

### ISSUE THREAD

**Issue by jbartolome** [AzureADQuickStarts/WebAPI-Bearer-DotNet#2]
Hello,
I'm able to build and run the TodoListService, however, when I attempt to add a new to-do list item in the client, I receive the following error:

![image](https://user-images.githubusercontent.com/19414037/30441767-32b82282-992f-11e7-942a-61f88d72a49b.png)

It occurs on the MainWindow.xaml.cs on Line 151 on the following line of code:
`HttpResponseMessage response = await httpClient.GetAsync(todoListBaseAddress + "/api/todolist");`

I've verified I've properly configured the Azure AD portal settings for both the client and service. I can also authenticate just fine.

Thanks.

**Comment by jmprieur** [comment]
See the referenced sample.
